name: 'Chromatic Deployment'
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: chromaui/action@v1
        with:
          projectToken: 79b4b54d6acb
          token: ${{ secrets.GITHUB_TOKEN }}
